// Code generated by goctl. DO NOT EDIT.
package types

type IdentifyRequest struct {
	Image string `json:"image"`        // base64编码的图片数据
	Age   int    `json:"age,optional"` // 可选：孩子年龄，用于优化识别
}

type IdentifyResponse struct {
	ObjectName     string   `json:"objectName"`        // 对象名称（中文）
	ObjectCategory string   `json:"objectCategory"`    // 对象类别：自然类/生活类/人文类
	Confidence     float64  `json:"confidence"`        // 识别置信度 0-1
	Keywords       []string `json:"keywords,optional"` // 相关关键词
}

type GenerateCardsRequest struct {
	ObjectName     string   `json:"objectName"`        // 对象名称
	ObjectCategory string   `json:"objectCategory"`    // 对象类别
	Age            int      `json:"age"`               // 孩子年龄（必填，用于内容分级）
	Keywords       []string `json:"keywords,optional"` // 相关关键词
}

type CardContent struct {
	Type    string      `json:"type"`    // 卡片类型：science/poetry/english
	Title   string      `json:"title"`   // 卡片标题
	Content interface{} `json:"content"` // 卡片内容（根据类型不同结构不同）
}

type GenerateCardsResponse struct {
	Cards []CardContent `json:"cards"` // 三张知识卡片
}

type CreateShareRequest struct {
	ExplorationRecords []ExplorationRecord `json:"explorationRecords"` // 探索记录列表
	CollectedCards     []KnowledgeCard     `json:"collectedCards"`     // 收藏的卡片列表
}

type ExplorationRecord struct {
	Id             string        `json:"id"`             // 探索记录ID
	Timestamp      string        `json:"timestamp"`      // 探索时间
	ObjectName     string        `json:"objectName"`     // 对象名称
	ObjectCategory string        `json:"objectCategory"` // 对象类别
	Age            int           `json:"age"`            // 探索时的年龄
	Cards          []CardContent `json:"cards"`          // 生成的知识卡片
}

type KnowledgeCard struct {
	Id            string      `json:"id"`                   // 卡片ID
	ExplorationId string      `json:"explorationId"`        // 关联的探索记录ID
	Type          string      `json:"type"`                 // 卡片类型
	Title         string      `json:"title"`                // 卡片标题
	Content       interface{} `json:"content"`              // 卡片内容
	CollectedAt   string      `json:"collectedAt,optional"` // 收藏时间
}

type CreateShareResponse struct {
	ShareId   string `json:"shareId"`   // 分享链接ID
	ShareUrl  string `json:"shareUrl"`  // 分享链接URL
	ExpiresAt string `json:"expiresAt"` // 过期时间
}

type GetShareResponse struct {
	ExplorationRecords []ExplorationRecord `json:"explorationRecords"` // 探索记录列表
	CollectedCards     []KnowledgeCard     `json:"collectedCards"`     // 收藏的卡片列表
	CreatedAt          string              `json:"createdAt"`          // 创建时间
	ExpiresAt          string              `json:"expiresAt"`          // 过期时间
}

type GenerateReportRequest struct {
	ShareId string `json:"shareId"` // 分享链接ID
}

type GenerateReportResponse struct {
	TotalExplorations    int             `json:"totalExplorations"`    // 总探索次数
	TotalCollectedCards  int             `json:"totalCollectedCards"`  // 总收藏卡片数
	CategoryDistribution map[string]int  `json:"categoryDistribution"` // 类别分布
	RecentCards          []KnowledgeCard `json:"recentCards"`          // 最近收藏的卡片（最多10张）
	GeneratedAt          string          `json:"generatedAt"`          // 生成时间
}

type ErrorResponse struct {
	Code    int    `json:"code"`            // 错误码
	Message string `json:"message"`         // 错误信息
	Detail  string `json:"detail,optional"` // 错误详情
}
