// Code generated by goctl. DO NOT EDIT.
package types

type IdentifyRequest struct {
	Image string `json:"image"`        // base64编码的图片数据
	Age   int    `json:"age,optional"` // 可选：孩子年龄，用于优化识别
}

type IdentifyResponse struct {
	ObjectName     string   `json:"objectName"`        // 对象名称（中文）
	ObjectCategory string   `json:"objectCategory"`    // 对象类别：自然类/生活类/人文类
	Confidence     float64  `json:"confidence"`        // 识别置信度 0-1
	Keywords       []string `json:"keywords,optional"` // 相关关键词
}

type GenerateCardsRequest struct {
	ObjectName     string   `json:"objectName"`        // 对象名称
	ObjectCategory string   `json:"objectCategory"`    // 对象类别
	Age            int      `json:"age"`               // 孩子年龄（必填，用于内容分级）
	Keywords       []string `json:"keywords,optional"` // 相关关键词
}

type CardContent struct {
	Type    string      `json:"type"`    // 卡片类型：science/poetry/english
	Title   string      `json:"title"`   // 卡片标题
	Content interface{} `json:"content"` // 卡片内容（根据类型不同结构不同）
}

type GenerateCardsResponse struct {
	Cards []CardContent `json:"cards"` // 三张知识卡片
}

type CreateShareRequest struct {
	ExplorationRecords []ExplorationRecord `json:"explorationRecords"` // 探索记录列表
	CollectedCards     []KnowledgeCard     `json:"collectedCards"`     // 收藏的卡片列表
}

type ExplorationRecord struct {
	Id             string        `json:"id"`             // 探索记录ID
	Timestamp      string        `json:"timestamp"`      // 探索时间
	ObjectName     string        `json:"objectName"`     // 对象名称
	ObjectCategory string        `json:"objectCategory"` // 对象类别
	Age            int           `json:"age"`            // 探索时的年龄
	Cards          []CardContent `json:"cards"`          // 生成的知识卡片
}

type KnowledgeCard struct {
	Id            string      `json:"id"`                   // 卡片ID
	ExplorationId string      `json:"explorationId"`        // 关联的探索记录ID
	Type          string      `json:"type"`                 // 卡片类型
	Title         string      `json:"title"`                // 卡片标题
	Content       interface{} `json:"content"`              // 卡片内容
	CollectedAt   string      `json:"collectedAt,optional"` // 收藏时间
}

type CreateShareResponse struct {
	ShareId   string `json:"shareId"`   // 分享链接ID
	ShareUrl  string `json:"shareUrl"`  // 分享链接URL
	ExpiresAt string `json:"expiresAt"` // 过期时间
}

type GetShareResponse struct {
	ExplorationRecords []ExplorationRecord `json:"explorationRecords"` // 探索记录列表
	CollectedCards     []KnowledgeCard     `json:"collectedCards"`     // 收藏的卡片列表
	CreatedAt          string              `json:"createdAt"`          // 创建时间
	ExpiresAt          string              `json:"expiresAt"`          // 过期时间
}

type GenerateReportRequest struct {
	ShareId string `json:"shareId"` // 分享链接ID
}

type GenerateReportResponse struct {
	TotalExplorations    int             `json:"totalExplorations"`    // 总探索次数
	TotalCollectedCards  int             `json:"totalCollectedCards"`  // 总收藏卡片数
	CategoryDistribution map[string]int  `json:"categoryDistribution"` // 类别分布
	RecentCards          []KnowledgeCard `json:"recentCards"`          // 最近收藏的卡片（最多10张）
	GeneratedAt          string          `json:"generatedAt"`          // 生成时间
}

type ErrorResponse struct {
	Code    int    `json:"code"`            // 错误码
	Message string `json:"message"`         // 错误信息
	Detail  string `json:"detail,optional"` // 错误详情
}

// 对话相关类型（从 explore.api 定义）
type ConversationMessage struct {
	Id        string      `json:"id"`                  // 消息ID
	Type      string      `json:"type"`                // 消息类型：user/assistant/system
	Content   interface{} `json:"content"`             // 消息内容（文本、图片、语音、卡片等）
	Timestamp string      `json:"timestamp"`           // 消息时间戳
	SessionId string      `json:"sessionId,optional"`  // 会话ID
}

type ConversationSession struct {
	Id        string               `json:"id"`        // 会话ID
	Messages  []ConversationMessage `json:"messages"` // 消息列表
	CreatedAt string               `json:"createdAt"` // 创建时间
	UpdatedAt string               `json:"updatedAt"` // 更新时间
}

type IntentRequest struct {
	Message   string               `json:"message"`                 // 用户消息（文本）
	SessionId string               `json:"sessionId,optional"`     // 会话ID（可选，用于上下文理解）
	Context   []ConversationMessage `json:"context,optional"` // 上下文消息（可选）
}

type IntentResult struct {
	Intent     string  `json:"intent"`     // 意图类型：generate_cards/text_response
	Confidence float64 `json:"confidence"` // 置信度 0-1
	Reason     string  `json:"reason,optional"` // 识别原因（可选）
}

type ConversationRequest struct {
	Message   string `json:"message"`                 // 用户消息（文本）
	Image     string `json:"image,optional"`          // 图片（base64，可选）
	Voice     string `json:"voice,optional"`          // 语音（base64，可选）
	SessionId string `json:"sessionId,optional"`      // 会话ID（可选）
}

type ConversationResponse struct {
	Message   ConversationMessage `json:"message"`   // 回复消息
	SessionId string              `json:"sessionId"`  // 会话ID
	Type      string              `json:"type"`       // 响应类型：text/cards
}

type VoiceRequest struct {
	Audio     string `json:"audio"`                  // base64编码的音频数据
	SessionId string `json:"sessionId,optional"`     // 会话ID（可选）
}

type VoiceResponse struct {
	Text      string `json:"text"`                  // 识别的文本
	SessionId string `json:"sessionId,optional"`    // 会话ID（可选）
}
