// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/tango/explore/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/explore/identify",
				Handler: IdentifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/explore/generate-cards",
				Handler: GenerateCardsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/share/create",
				Handler: CreateShareHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/share/:shareId",
				Handler: GetShareHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/share/report",
				Handler: GenerateReportHandler(serverCtx),
			},
		},
	)
}
