// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"github.com/tango/explore/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/badge/stats",
				Handler: GetBadgeStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/conversation/intent",
				Handler: IntentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/conversation/message",
				Handler: ConversationHandler(serverCtx),
			},
		{
			Method:  http.MethodPost,
			Path:    "/api/conversation/stream",
			Handler: StreamConversationHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/conversation/agent",
			Handler: AgentConversationHandler(serverCtx),
		},
			{
				Method:  http.MethodPost,
				Path:    "/api/explore/generate-cards",
				Handler: GenerateCardsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/explore/identify",
				Handler: IdentifyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/share/:shareId",
				Handler: GetShareHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/share/create",
				Handler: CreateShareHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/upload/image",
				Handler: UploadHandler(serverCtx),
			},
		},
	)
}
